"""init test system models

Revision ID: 418e1d2f64eb
Revises: 7134642db886
Create Date: 2025-11-25 10:33:34.148996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '418e1d2f64eb'
down_revision: Union[str, Sequence[str], None] = '7134642db886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Dlya sebya: migracionnyy shag (upgrade).
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_run_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('request', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['test_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_run_logs_run_id'), 'test_run_logs', ['run_id'], unique=False)
    op.create_index(op.f('ix_logs_test_case_run_id'), 'logs', ['test_case_run_id'], unique=False)
    op.create_index(op.f('ix_schedules_is_active'), 'schedules', ['is_active'], unique=False)
    op.create_index(op.f('ix_test_case_runs_test_case_id'), 'test_case_runs', ['test_case_id'], unique=False)
    op.create_index(op.f('ix_test_case_runs_test_run_id'), 'test_case_runs', ['test_run_id'], unique=False)
    op.create_index(op.f('ix_test_case_runs_xml_scenario_id'), 'test_case_runs', ['xml_scenario_id'], unique=False)
    op.create_index(op.f('ix_test_cases_group_id'), 'test_cases', ['group_id'], unique=False)
    op.add_column('test_runs', sa.Column('scenario_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_test_runs_id'), 'test_runs', ['id'], unique=False)
    op.create_index(op.f('ix_test_runs_scenario_id'), 'test_runs', ['scenario_id'], unique=False)
    op.create_foreign_key(None, 'test_runs', 'xml_scenarios', ['scenario_id'], ['id'], ondelete='SET NULL')
    op.drop_column('test_runs', 'created_at')
    op.add_column('xml_scenarios', sa.Column('filename', sa.String(length=255), nullable=False))
    op.add_column('xml_scenarios', sa.Column('uploaded_at', sa.DateTime(), nullable=False))
    op.alter_column('xml_scenarios', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_xml_scenarios_filename'), 'xml_scenarios', ['filename'], unique=False)
    op.create_index(op.f('ix_xml_scenarios_id'), 'xml_scenarios', ['id'], unique=False)
    op.drop_column('xml_scenarios', 'name')
    op.drop_column('xml_scenarios', 'is_system')
    op.drop_column('xml_scenarios', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # Dlya sebya: migracionnyy shag (downgrade).
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('xml_scenarios', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('xml_scenarios', sa.Column('is_system', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('xml_scenarios', sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_xml_scenarios_id'), table_name='xml_scenarios')
    op.drop_index(op.f('ix_xml_scenarios_filename'), table_name='xml_scenarios')
    op.alter_column('xml_scenarios', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('xml_scenarios', 'uploaded_at')
    op.drop_column('xml_scenarios', 'filename')
    op.add_column('test_runs', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_test_runs_scenario_id'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_id'), table_name='test_runs')
    op.drop_column('test_runs', 'scenario_id')
    op.drop_index(op.f('ix_test_cases_group_id'), table_name='test_cases')
    op.drop_index(op.f('ix_test_case_runs_xml_scenario_id'), table_name='test_case_runs')
    op.drop_index(op.f('ix_test_case_runs_test_run_id'), table_name='test_case_runs')
    op.drop_index(op.f('ix_test_case_runs_test_case_id'), table_name='test_case_runs')
    op.drop_index(op.f('ix_schedules_is_active'), table_name='schedules')
    op.drop_index(op.f('ix_logs_test_case_run_id'), table_name='logs')
    op.drop_index(op.f('ix_test_run_logs_run_id'), table_name='test_run_logs')
    op.drop_table('test_run_logs')
    # ### end Alembic commands ###
