# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Ai_Control.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Ai_Control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Ai_Report_pb2 as Ai__Report__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x41i_Control.proto\x12\x08\x61i.proto\x1a\x0f\x41i_Report.proto\"\xa3\x01\n\rControlAction\x12*\n\x04type\x18\x01 \x02(\x0e\x32\x1c.ai.proto.ControlAction.Type\x12\x0f\n\x07\x63\x61rd_id\x18\x02 \x02(\t\"U\n\x04Type\x12\x13\n\x0f\x43\x41_KILL_PROGRAM\x10\x01\x12\x13\n\x0f\x43\x41_RAISE_WINDOW\x10\x02\x12\x11\n\rCA_START_WORK\x10\x03\x12\x10\n\x0c\x43\x41_STOP_WORK\x10\x04\"?\n\x14\x43ontrolActionRequest\x12\'\n\x06\x61\x63tion\x18\x01 \x02(\x0b\x32\x17.ai.proto.ControlAction\"9\n\x15\x43ontrolActionResponse\x12 \n\x06report\x18\x01 \x02(\x0b\x32\x10.ai.proto.Report\";\n\x12SetWorkModeRequest\x12\x14\n\x0cwork_mode_id\x18\x01 \x02(\t\x12\x0f\n\x07\x63\x61rd_id\x18\x02 \x01(\t\"M\n\x13SetWorkModeResponse\x12\x14\n\x0cwork_mode_id\x18\x01 \x02(\t\x12 \n\x06report\x18\x02 \x02(\x0b\x32\x10.ai.proto.Report')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Ai_Control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTROLACTION']._serialized_start=48
  _globals['_CONTROLACTION']._serialized_end=211
  _globals['_CONTROLACTION_TYPE']._serialized_start=126
  _globals['_CONTROLACTION_TYPE']._serialized_end=211
  _globals['_CONTROLACTIONREQUEST']._serialized_start=213
  _globals['_CONTROLACTIONREQUEST']._serialized_end=276
  _globals['_CONTROLACTIONRESPONSE']._serialized_start=278
  _globals['_CONTROLACTIONRESPONSE']._serialized_end=335
  _globals['_SETWORKMODEREQUEST']._serialized_start=337
  _globals['_SETWORKMODEREQUEST']._serialized_end=396
  _globals['_SETWORKMODERESPONSE']._serialized_start=398
  _globals['_SETWORKMODERESPONSE']._serialized_end=475
# @@protoc_insertion_point(module_scope)
