# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Ai_FacilityStructure.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Ai_FacilityStructure.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Ai_Common_pb2 as Ai__Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x41i_FacilityStructure.proto\x12\x11\x61i.proto.facility\x1a\x0f\x41i_Common.proto\"\'\n\x06UnitId\x12\x1d\n\x05value\x18\x01 \x02(\x0b\x32\x0e.ai.proto.UUID\"U\n\x04Unit\x12*\n\x07unit_id\x18\x01 \x02(\x0b\x32\x19.ai.proto.facility.UnitId\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"/\n\x05Units\x12&\n\x05units\x18\x01 \x03(\x0b\x32\x17.ai.proto.facility.Unit\"(\n\x07GroupId\x12\x1d\n\x05value\x18\x01 \x02(\x0b\x32\x0e.ai.proto.UUID\"\xdf\x01\n\x05Group\x12,\n\x08group_id\x18\x01 \x02(\x0b\x32\x1a.ai.proto.facility.GroupId\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12*\n\x06slaves\x18\x0b \x03(\x0b\x32\x1a.ai.proto.facility.GroupId\x12(\n\x05units\x18\x0c \x03(\x0b\x32\x19.ai.proto.facility.UnitId\x12/\n\x08hardware\x18\r \x03(\x0b\x32\x1d.ai.proto.facility.HardwareId\"\\\n\x06Groups\x12(\n\x04head\x18\x01 \x02(\x0b\x32\x1a.ai.proto.facility.GroupId\x12(\n\x06groups\x18\x02 \x03(\x0b\x32\x18.ai.proto.facility.Group\"+\n\nHardwareId\x12\x1d\n\x05value\x18\x01 \x02(\x0b\x32\x0e.ai.proto.UUID\"L\n\x08Hardware\x12\x32\n\x0bhardware_id\x18\x01 \x02(\x0b\x32\x1d.ai.proto.facility.HardwareId\x12\x0c\n\x04name\x18\x02 \x02(\t\"=\n\x0cHardwareList\x12-\n\x08hardware\x18\x01 \x03(\x0b\x32\x1b.ai.proto.facility.Hardware\"\x91\x01\n\x08\x46\x61\x63ility\x12)\n\x06groups\x18\x01 \x02(\x0b\x32\x19.ai.proto.facility.Groups\x12\'\n\x05units\x18\x02 \x02(\x0b\x32\x18.ai.proto.facility.Units\x12\x31\n\x08hardware\x18\x03 \x02(\x0b\x32\x1f.ai.proto.facility.HardwareList\"\x11\n\x0f\x46\x61\x63ilityRequest\"A\n\x10\x46\x61\x63ilityResponse\x12-\n\x08\x66\x61\x63ility\x18\x01 \x02(\x0b\x32\x1b.ai.proto.facility.Facility\"C\n\x12\x46\x61\x63ilityIndication\x12-\n\x08\x66\x61\x63ility\x18\x01 \x02(\x0b\x32\x1b.ai.proto.facility.Facility')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Ai_FacilityStructure_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UNITID']._serialized_start=66
  _globals['_UNITID']._serialized_end=105
  _globals['_UNIT']._serialized_start=107
  _globals['_UNIT']._serialized_end=192
  _globals['_UNITS']._serialized_start=194
  _globals['_UNITS']._serialized_end=241
  _globals['_GROUPID']._serialized_start=243
  _globals['_GROUPID']._serialized_end=283
  _globals['_GROUP']._serialized_start=286
  _globals['_GROUP']._serialized_end=509
  _globals['_GROUPS']._serialized_start=511
  _globals['_GROUPS']._serialized_end=603
  _globals['_HARDWAREID']._serialized_start=605
  _globals['_HARDWAREID']._serialized_end=648
  _globals['_HARDWARE']._serialized_start=650
  _globals['_HARDWARE']._serialized_end=726
  _globals['_HARDWARELIST']._serialized_start=728
  _globals['_HARDWARELIST']._serialized_end=789
  _globals['_FACILITY']._serialized_start=792
  _globals['_FACILITY']._serialized_end=937
  _globals['_FACILITYREQUEST']._serialized_start=939
  _globals['_FACILITYREQUEST']._serialized_end=956
  _globals['_FACILITYRESPONSE']._serialized_start=958
  _globals['_FACILITYRESPONSE']._serialized_end=1023
  _globals['_FACILITYINDICATION']._serialized_start=1025
  _globals['_FACILITYINDICATION']._serialized_end=1092
# @@protoc_insertion_point(module_scope)
