# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Ai_Handshake.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Ai_Handshake.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Ai_Report_pb2 as Ai__Report__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x41i_Handshake.proto\x12\x08\x61i.proto\x1a\x0f\x41i_Report.proto\"\x87\x02\n\x0fSoftwareVersion\x12 \n\x18protocol_version_current\x18\x01 \x02(\r\x12&\n\x1eprotocol_version_min_supported\x18\x02 \x02(\r\x12\x18\n\x10software_version\x18\x0b \x01(\t\x12\x17\n\x0f\x62uild_date_time\x18\x0c \x01(\t\x12\x15\n\rsoftware_name\x18\x14 \x01(\t\x12\x14\n\x0c\x63\x61pabilities\x18\x15 \x03(\t\"%\n\x16ProtocolCurrentVersion\x12\x0b\n\x07\x43URRENT\x10\x10\"#\n\x18ProtocolSupportedVersion\x12\x07\n\x03MIN\x10\x07\"T\n\x10HandshakeRequest\x12\x0f\n\x07host_id\x18\x01 \x02(\t\x12/\n\x0chost_version\x18\x02 \x02(\x0b\x32\x19.ai.proto.SoftwareVersion\"l\n\x11HandshakeResponse\x12 \n\x06report\x18\x01 \x02(\x0b\x32\x10.ai.proto.Report\x12\x35\n\x12integrator_version\x18\x02 \x02(\x0b\x32\x19.ai.proto.SoftwareVersion\"\xaf\x01\n\x11LoginNodusRequest\x12+\n\toperation\x18\x01 \x02(\x0e\x32\x18.ai.proto.LoginOperation\x12=\n\x0clogin_params\x18\x02 \x01(\x0b\x32\'.ai.proto.LoginNodusRequest.LoginParams\x1a.\n\x0bLoginParams\x12\r\n\x05login\x18\x01 \x02(\t\x12\x10\n\x08password\x18\x02 \x02(\t\"\x8f\x01\n\x12LoginNodusResponse\x12 \n\x06report\x18\x01 \x02(\x0b\x32\x10.ai.proto.Report\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\x12\x0e\n\x06\x64\x65vice\x18\x04 \x01(\t\x12+\n\toperation\x18\x05 \x01(\x0e\x32\x18.ai.proto.LoginOperation\"l\n\x11LoginNotification\x12+\n\toperation\x18\x01 \x02(\x0e\x32\x18.ai.proto.LoginOperation\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\x12\x0e\n\x06\x64\x65vice\x18\x04 \x01(\t*\'\n\x0eLoginOperation\x12\t\n\x05LOGIN\x10\x01\x12\n\n\x06LOGOUT\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Ai_Handshake_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINOPERATION']._serialized_start=945
  _globals['_LOGINOPERATION']._serialized_end=984
  _globals['_SOFTWAREVERSION']._serialized_start=50
  _globals['_SOFTWAREVERSION']._serialized_end=313
  _globals['_SOFTWAREVERSION_PROTOCOLCURRENTVERSION']._serialized_start=239
  _globals['_SOFTWAREVERSION_PROTOCOLCURRENTVERSION']._serialized_end=276
  _globals['_SOFTWAREVERSION_PROTOCOLSUPPORTEDVERSION']._serialized_start=278
  _globals['_SOFTWAREVERSION_PROTOCOLSUPPORTEDVERSION']._serialized_end=313
  _globals['_HANDSHAKEREQUEST']._serialized_start=315
  _globals['_HANDSHAKEREQUEST']._serialized_end=399
  _globals['_HANDSHAKERESPONSE']._serialized_start=401
  _globals['_HANDSHAKERESPONSE']._serialized_end=509
  _globals['_LOGINNODUSREQUEST']._serialized_start=512
  _globals['_LOGINNODUSREQUEST']._serialized_end=687
  _globals['_LOGINNODUSREQUEST_LOGINPARAMS']._serialized_start=641
  _globals['_LOGINNODUSREQUEST_LOGINPARAMS']._serialized_end=687
  _globals['_LOGINNODUSRESPONSE']._serialized_start=690
  _globals['_LOGINNODUSRESPONSE']._serialized_end=833
  _globals['_LOGINNOTIFICATION']._serialized_start=835
  _globals['_LOGINNOTIFICATION']._serialized_end=943
# @@protoc_insertion_point(module_scope)
