# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Ai_ModuleLaunch.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Ai_ModuleLaunch.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Ai_Report_pb2 as Ai__Report__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x41i_ModuleLaunch.proto\x12\x08\x61i.proto\x1a\x0f\x41i_Report.proto\"q\n\x13ModuleLaunchRequest\x12\x12\n\nmoduleName\x18\x01 \x02(\t\x12\r\n\x05group\x18\x02 \x01(\t\x12\x12\n\nlaunchMode\x18\x03 \x01(\t\x12\x10\n\x08training\x18\x04 \x01(\x08\x12\x11\n\tmessageId\x18\x05 \x02(\x05\"\x80\x01\n\x14ModuleLaunchResponse\x12 \n\x06report\x18\x01 \x02(\x0b\x32\x10.ai.proto.Report\x12\x12\n\nmoduleName\x18\x02 \x02(\t\x12\r\n\x05group\x18\x03 \x01(\t\x12\x10\n\x08waitTime\x18\x04 \x01(\x05\x12\x11\n\tmessageId\x18\x05 \x02(\x05\"l\n\x12ModuleLaunchResult\x12 \n\x06report\x18\x01 \x02(\x0b\x32\x10.ai.proto.Report\x12\x12\n\nmoduleName\x18\x02 \x02(\t\x12\r\n\x05group\x18\x03 \x01(\t\x12\x11\n\tmessageId\x18\x04 \x02(\x05\"I\n\x11ModuleStopRequest\x12\x12\n\nmoduleName\x18\x01 \x02(\t\x12\r\n\x05group\x18\x02 \x01(\t\x12\x11\n\tmessageId\x18\x03 \x02(\x05\"~\n\x12ModuleStopResponse\x12 \n\x06report\x18\x01 \x02(\x0b\x32\x10.ai.proto.Report\x12\x12\n\nmoduleName\x18\x02 \x02(\t\x12\r\n\x05group\x18\x03 \x01(\t\x12\x10\n\x08waitTime\x18\x04 \x01(\x05\x12\x11\n\tmessageId\x18\x05 \x02(\x05\"j\n\x10ModuleStopResult\x12 \n\x06report\x18\x01 \x02(\x0b\x32\x10.ai.proto.Report\x12\x12\n\nmoduleName\x18\x02 \x02(\t\x12\r\n\x05group\x18\x03 \x01(\t\x12\x11\n\tmessageId\x18\x04 \x02(\x05\"c\n\x16ModuleStatusIndication\x12&\n\x06status\x18\x01 \x02(\x0e\x32\x16.ai.proto.ModuleStatus\x12\x12\n\nmoduleName\x18\x02 \x02(\t\x12\r\n\x05group\x18\x03 \x01(\t*\"\n\x0cModuleStatus\x12\x12\n\x0eMODULE_STOPPED\x10\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Ai_ModuleLaunch_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODULESTATUS']._serialized_start=820
  _globals['_MODULESTATUS']._serialized_end=854
  _globals['_MODULELAUNCHREQUEST']._serialized_start=52
  _globals['_MODULELAUNCHREQUEST']._serialized_end=165
  _globals['_MODULELAUNCHRESPONSE']._serialized_start=168
  _globals['_MODULELAUNCHRESPONSE']._serialized_end=296
  _globals['_MODULELAUNCHRESULT']._serialized_start=298
  _globals['_MODULELAUNCHRESULT']._serialized_end=406
  _globals['_MODULESTOPREQUEST']._serialized_start=408
  _globals['_MODULESTOPREQUEST']._serialized_end=481
  _globals['_MODULESTOPRESPONSE']._serialized_start=483
  _globals['_MODULESTOPRESPONSE']._serialized_end=609
  _globals['_MODULESTOPRESULT']._serialized_start=611
  _globals['_MODULESTOPRESULT']._serialized_end=717
  _globals['_MODULESTATUSINDICATION']._serialized_start=719
  _globals['_MODULESTATUSINDICATION']._serialized_end=818
# @@protoc_insertion_point(module_scope)
