# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Ai_NetworkInfo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Ai_NetworkInfo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Ai_Common_pb2 as Ai__Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x41i_NetworkInfo.proto\x12\x08\x61i.proto\x1a\x0f\x41i_Common.proto\"\xc8\x01\n\nModuleInfo\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x14\n\x0c\x63\x61pabilities\x18\x04 \x03(\t\x12\x10\n\x08\x61lias_id\x18\x05 \x01(\t\x12\x19\n\nauthorized\x18\x06 \x01(\x08:\x05\x66\x61lse\x12\x0e\n\x06online\x18\x07 \x01(\x08\x12\x11\n\tclient_id\x18\x08 \x01(\t\x12)\n\x0blast_online\x18\t \x01(\x0b\x32\x14.ai.proto.SystemTime\"\xc0\x01\n\x0bMachineInfo\x12\x12\n\nmachine_id\x18\x01 \x02(\t\x12\x14\n\x0cmachine_name\x18\x02 \x01(\t\x12%\n\x07modules\x18\x03 \x03(\x0b\x32\x14.ai.proto.ModuleInfo\x12\x11\n\tlocalhost\x18\x04 \x01(\x08\x12\x12\n\ngroup_name\x18\x05 \x01(\t\x12\x0e\n\x06online\x18\x06 \x01(\x08\x12\x12\n\nip_address\x18\x07 \x01(\t\x12\x15\n\rmachine_alias\x18\x08 \x01(\t\";\n\x14ModuleListIndication\x12#\n\x04list\x18\x01 \x03(\x0b\x32\x15.ai.proto.MachineInfo\"\'\n\x11ModuleListRequest\x12\x12\n\nmachine_id\x18\x01 \x01(\t\"9\n\x12ModuleListResponse\x12#\n\x04list\x18\x01 \x03(\x0b\x32\x15.ai.proto.MachineInfo\"\xa3\x02\n\x08UserInfo\x12\x0f\n\x07user_id\x18\x01 \x02(\t\x12\x11\n\tuser_name\x18\x02 \x01(\t\x12\x11\n\tuser_role\x18\x03 \x01(\t\x12\x11\n\tuser_rank\x18\n \x01(\t\x12\x11\n\tsuperiors\x18\x04 \x03(\t\x12\x14\n\x0csubordinates\x18\x05 \x03(\t\x12\x10\n\x08machines\x18\x06 \x03(\t\x12\x11\n\tlocalhost\x18\x07 \x01(\x08\x12)\n\x06status\x18\x08 \x01(\x0e\x32\x19.ai.proto.UserInfo.Status\x12\'\n\taway_time\x18\t \x01(\x0b\x32\x14.ai.proto.SystemTime\"+\n\x06Status\x12\n\n\x06ONLINE\x10\x01\x12\x0b\n\x07OFFLINE\x10\x02\x12\x08\n\x04\x41WAY\x10\x03\"6\n\x12UserListIndication\x12 \n\x04list\x18\x01 \x03(\x0b\x32\x12.ai.proto.UserInfo\"\"\n\x0fUserListRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"4\n\x10UserListResponse\x12 \n\x04list\x18\x01 \x03(\x0b\x32\x12.ai.proto.UserInfo')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Ai_NetworkInfo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODULEINFO']._serialized_start=52
  _globals['_MODULEINFO']._serialized_end=252
  _globals['_MACHINEINFO']._serialized_start=255
  _globals['_MACHINEINFO']._serialized_end=447
  _globals['_MODULELISTINDICATION']._serialized_start=449
  _globals['_MODULELISTINDICATION']._serialized_end=508
  _globals['_MODULELISTREQUEST']._serialized_start=510
  _globals['_MODULELISTREQUEST']._serialized_end=549
  _globals['_MODULELISTRESPONSE']._serialized_start=551
  _globals['_MODULELISTRESPONSE']._serialized_end=608
  _globals['_USERINFO']._serialized_start=611
  _globals['_USERINFO']._serialized_end=902
  _globals['_USERINFO_STATUS']._serialized_start=859
  _globals['_USERINFO_STATUS']._serialized_end=902
  _globals['_USERLISTINDICATION']._serialized_start=904
  _globals['_USERLISTINDICATION']._serialized_end=958
  _globals['_USERLISTREQUEST']._serialized_start=960
  _globals['_USERLISTREQUEST']._serialized_end=994
  _globals['_USERLISTRESPONSE']._serialized_start=996
  _globals['_USERLISTRESPONSE']._serialized_end=1048
# @@protoc_insertion_point(module_scope)
