# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Ai_PostParameters.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Ai_PostParameters.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Ai_Report_pb2 as Ai__Report__pb2
from . import Ai_Parameters_pb2 as Ai__Parameters__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x41i_PostParameters.proto\x12\x08\x61i.proto\x1a\x0f\x41i_Report.proto\x1a\x13\x41i_Parameters.proto\"?\n\x14SetParametersRequest\x12\'\n\nparameters\x18\x01 \x03(\x0b\x32\x13.ai.proto.Parameter\"b\n\x15SetParametersResponse\x12 \n\x06report\x18\x01 \x02(\x0b\x32\x10.ai.proto.Report\x12\'\n\nparameters\x18\x02 \x03(\x0b\x32\x13.ai.proto.Parameter')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Ai_PostParameters_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETPARAMETERSREQUEST']._serialized_start=75
  _globals['_SETPARAMETERSREQUEST']._serialized_end=138
  _globals['_SETPARAMETERSRESPONSE']._serialized_start=140
  _globals['_SETPARAMETERSRESPONSE']._serialized_end=238
# @@protoc_insertion_point(module_scope)
