# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Ai_Report.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Ai_Report.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x41i_Report.proto\x12\x08\x61i.proto\"G\n\x06Report\x12(\n\x04\x63ode\x18\x01 \x02(\x0e\x32\x14.ai.proto.ReportCode:\x04\x44ONE\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t*\xd0\x06\n\nReportCode\x12\x08\n\x04\x44ONE\x10\x00\x12\x11\n\rERR_UNDEFINED\x10\x01\x12!\n\x1d\x45RR_PROTOCOL_VERSION_MISMATCH\x10\x64\x12$\n ERR_UNSUPPORTED_PROTOCOL_VERSION\x10\x65\x12\x1e\n\x1a\x45RR_PARAMETERS_NOT_APPLIED\x10\x66\x12\x19\n\x15\x45RR_STATE_NOT_APPLIED\x10g\x12 \n\x1c\x45RR_MODULE_ALREADY_CONNECTED\x10h\x12\x18\n\x14\x45RR_NETWORK_OVERLOAD\x10i\x12\x18\n\x13\x45RR_NOT_ENOUGH_DATA\x10\x96\x01\x12\x14\n\x0f\x45RR_ID_MISMATCH\x10\x97\x01\x12\x1d\n\x18\x45RR_NOT_SUPPORTED_ACTION\x10\x98\x01\x12\x19\n\x14\x45RR_INVALID_DOCUMENT\x10\x99\x01\x12\x11\n\x0c\x45RR_ID_EXIST\x10\x9a\x01\x12\x18\n\x13\x45RR_CLIENT_MISMATCH\x10\x9b\x01\x12\x17\n\x12\x45RR_STATE_MISMATCH\x10\x9c\x01\x12\x16\n\x11\x45RR_FILE_CANCELED\x10\xa1\x01\x12\x17\n\x12\x45RR_FILE_NOT_FOUND\x10\xa2\x01\x12\x14\n\x0f\x46ILE_INCOMPLETE\x10\xa3\x01\x12\x18\n\x13\x45RR_HOST_NOT_EXISTS\x10\xaa\x01\x12\x16\n\x11\x45RR_ACCESS_DENIED\x10\xb4\x01\x12\x17\n\x12\x45RR_SESSION_OPENED\x10\xb5\x01\x12 \n\x1b\x45RR_LAUNCH_MODULE_NOT_FOUND\x10\xbe\x01\x12 \n\x1b\x45RR_LAUNCH_BINARY_NOT_FOUND\x10\xbf\x01\x12\x15\n\x10\x45RR_LAUNCH_ERROR\x10\xc0\x01\x12\x1e\n\x19\x45RR_LAUNCH_MODULE_TIMEOUT\x10\xc1\x01\x12%\n ERR_MODULE_UNSUPPORTED_PROTOTCOL\x10\xc2\x01\x12\x1e\n\x19\x45RR_STOP_MODULE_NOT_FOUND\x10\xc3\x01\x12!\n\x1c\x45RR_STOP_MODULE_NOT_RESPONSE\x10\xc4\x01\x12\x1c\n\x17\x45RR_STOP_MODULE_TIMEOUT\x10\xc5\x01\x12 \n\x1b\x45RR_MODULE_ALREADY_LAUNCHED\x10\xc6\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Ai_Report_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REPORTCODE']._serialized_start=103
  _globals['_REPORTCODE']._serialized_end=951
  _globals['_REPORT']._serialized_start=29
  _globals['_REPORT']._serialized_end=100
# @@protoc_insertion_point(module_scope)
