# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Ai_StopAction.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Ai_StopAction.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Ai_Report_pb2 as Ai__Report__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x41i_StopAction.proto\x12\x08\x61i.proto\x1a\x0f\x41i_Report.proto\"\x13\n\x11StopActionRequest\"L\n\x12StopActionResponse\x12 \n\x06report\x18\x01 \x02(\x0b\x32\x10.ai.proto.Report\x12\x14\n\x0cstoppingTime\x18\x02 \x02(\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Ai_StopAction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STOPACTIONREQUEST']._serialized_start=50
  _globals['_STOPACTIONREQUEST']._serialized_end=69
  _globals['_STOPACTIONRESPONSE']._serialized_start=71
  _globals['_STOPACTIONRESPONSE']._serialized_end=147
# @@protoc_insertion_point(module_scope)
