# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Ai_TextMessage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Ai_TextMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Ai_Report_pb2 as Ai__Report__pb2
from . import Ai_Common_pb2 as Ai__Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x41i_TextMessage.proto\x12\x08\x61i.proto\x1a\x0f\x41i_Report.proto\x1a\x0f\x41i_Common.proto\"\xa4\x02\n\x12TextMessageRequest\x12\x1a\n\x02id\x18\x01 \x02(\x0b\x32\x0e.ai.proto.UUID\x12 \n\x06sender\x18\x02 \x02(\x0b\x32\x10.ai.proto.UserId\x12\"\n\x08receiver\x18\x03 \x02(\x0b\x32\x10.ai.proto.UserId\x12\"\n\x04time\x18\x04 \x02(\x0b\x32\x14.ai.proto.SystemTime\x12!\n\x05\x66iles\x18\x05 \x03(\x0b\x32\x12.ai.proto.FileInfo\x12\x32\n\x04type\x18\t \x02(\x0e\x32$.ai.proto.TextMessageRequest.MsgType\x12\x0c\n\x04\x64\x61ta\x18\n \x01(\x0c\"#\n\x07MsgType\x12\x0c\n\x08PERSONAL\x10\x01\x12\n\n\x06GLOBAL\x10\x02\"l\n\x13TextMessageResponse\x12\x1a\n\x02id\x18\x01 \x02(\x0b\x32\x0e.ai.proto.UUID\x12 \n\x06report\x18\x02 \x02(\x0b\x32\x10.ai.proto.Report\x12\x17\n\x0fsystem_response\x18\x03 \x01(\x08\"\xa8\x01\n\x17TextMessageNotification\x12\x1a\n\x02id\x18\x01 \x02(\x0b\x32\x0e.ai.proto.UUID\x12)\n\x05state\x18\x02 \x02(\x0e\x32\x1a.ai.proto.TextMessageState\x12\"\n\x04time\x18\x03 \x02(\x0b\x32\x14.ai.proto.SystemTime\x12\"\n\x08receiver\x18\x04 \x02(\x0b\x32\x10.ai.proto.UserId*)\n\x10TextMessageState\x12\x08\n\x04READ\x10\x01\x12\x0b\n\x07REMOVED\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Ai_TextMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTMESSAGESTATE']._serialized_start=644
  _globals['_TEXTMESSAGESTATE']._serialized_end=685
  _globals['_TEXTMESSAGEREQUEST']._serialized_start=69
  _globals['_TEXTMESSAGEREQUEST']._serialized_end=361
  _globals['_TEXTMESSAGEREQUEST_MSGTYPE']._serialized_start=326
  _globals['_TEXTMESSAGEREQUEST_MSGTYPE']._serialized_end=361
  _globals['_TEXTMESSAGERESPONSE']._serialized_start=363
  _globals['_TEXTMESSAGERESPONSE']._serialized_end=471
  _globals['_TEXTMESSAGENOTIFICATION']._serialized_start=474
  _globals['_TEXTMESSAGENOTIFICATION']._serialized_end=642
# @@protoc_insertion_point(module_scope)
