# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BinaryDataParam.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BinaryDataParam.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x42inaryDataParam.proto\x12\x08\x61i.proto\"\xe6\x02\n\x13\x42inaryDataParameter\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12:\n\x04type\x18\x03 \x01(\x0e\x32,.ai.proto.BinaryDataParameter.TypeBinaryData\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\"\xdd\x01\n\x0eTypeBinaryData\x12\x07\n\x03WAV\x10\x01\x12\x07\n\x03MP3\x10\x02\x12\x08\n\x04\x46LAC\x10\x03\x12\x07\n\x03\x41VI\x10\x14\x12\x07\n\x03MP4\x10\x15\x12\x07\n\x03\x42MP\x10(\x12\x08\n\x04JPEG\x10)\x12\x07\n\x03JPG\x10*\x12\x07\n\x03GIF\x10+\x12\x08\n\x04TIFF\x10,\x12\x07\n\x03PNG\x10-\x12\x07\n\x03\x44OC\x10<\x12\x08\n\x04\x44OCX\x10=\x12\x07\n\x03XLS\x10>\x12\x08\n\x04XLSX\x10?\x12\x07\n\x03ODT\x10@\x12\x07\n\x03PPT\x10\x41\x12\x07\n\x03TXT\x10\x42\x12\x08\n\x04JSON\x10\x43\x12\x07\n\x03XML\x10\x44\x12\x08\n\x04HTML\x10\x45\x12\x07\n\x03PDF\x10\x46')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BinaryDataParam_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BINARYDATAPARAMETER']._serialized_start=36
  _globals['_BINARYDATAPARAMETER']._serialized_end=394
  _globals['_BINARYDATAPARAMETER_TYPEBINARYDATA']._serialized_start=173
  _globals['_BINARYDATAPARAMETER_TYPEBINARYDATA']._serialized_end=394
# @@protoc_insertion_point(module_scope)
